import { Translations } from './types';

export const translations: Translations = {
  en: {
    loginWithGoogle: 'Login with Google',
    logout: 'Logout',
    dropPoop: 'Drop a Poop',
    dropping: 'Dropping...',
    locationError: 'Could not get location. Please enable permissions.',
    welcome: 'Welcome',
    totalDrops: 'Total Drops',
    noDropsYet: "You haven't dropped any poops yet.",
    poopMap: 'Poop Map',
    language: 'Language',
    poopDetails: 'Poop Details',
    location: 'Location',
    customLocation: 'Custom Location',
    rating: 'Experience Rating',
    uploadPhoto: 'Upload Photo',
    notes: 'Notes',
    save: 'Save',
    cancel: 'Cancel',
    excellent: 'Excellent',
    good: 'Good',
    average: 'Average',
    poor: 'Poor',
    terrible: 'Terrible',
    gettingLocation: 'Getting location...',
    takingPhoto: 'Taking photo...',
    friends: 'Friends',
    addFriend: 'Add Friend',
    friendRequests: 'Friend Requests',
    privacy: 'Privacy',
    private: 'Private',
    friendsOnly: 'Friends Only',
    public: 'Public',
    shareViaEmail: 'Share via Email',
    shareViaQR: 'Share via QR Code',
    shareViaLink: 'Share via Link',
    inviteFriend: 'Invite Friend',
    acceptRequest: 'Accept',
    rejectRequest: 'Reject',
    myQRCode: 'My QR Code',
    scanQRCode: 'Scan QR Code',
    // 互動功能翻譯
    like: 'Like',
    unlike: 'Unlike',
    comment: 'Comment',
    comments: 'Comments',
    likes: 'Likes',
    addComment: 'Add Comment',
    writeComment: 'Write a comment...',
    postComment: 'Post',
    deleteComment: 'Delete',
    likedBy: 'Liked by',
    noComments: 'No comments yet',
    noLikes: 'No likes yet',
    // 便便可見性篩選器翻譯
    allPoops: 'All Poops',
    myPoops: 'My Poops',
    friendPoops: 'Friend Poops',
    publicPoops: 'Public Poops',
    poopVisibility: 'Poop Visibility',
    selectPoopType: 'Select poop type to display',
    showAllVisible: 'Show all visible poops',
    showMyPoops: 'Show only my poop records',
    showFriendPoops: 'Show only friend poops',
    showPublicPoops: 'Show only public poops',
    switchVisibilityTip: 'Switch visibility to reduce poops on map',
    // 社交功能翻譯
    leaderboard: 'Leaderboard',
    achievements: 'Achievements',
    feed: 'Feed',
    challenges: 'Challenges',
    notifications: 'Notifications',
    statistics: 'Statistics',
    weeklyStats: 'Weekly Stats',
    // Header 統計翻譯
    today: 'Today',
    week: 'Week',
    total: 'Total',
    iconLegend: 'Icon Legend',
    myPoop: 'My Poop',
    friendPoop: 'Friend Poop',
    publicPoop: 'Public Poop',
    poopHistory: 'Poop History',
    weeklyTrend: 'Weekly Trend',
    // 社交菜單翻譯
    socialFeatures: 'Social Features',
    selectFeature: 'Select feature to use',
    viewPoopRanking: 'View poop ranking',
    myAchievementProgress: 'My achievement progress',
    friendActivity: 'Friend activity',
    participateInChallenges: 'Participate in challenges',
    messageNotifications: 'Message notifications',
    recordPoopToUnlock: 'Record poop to unlock more features',
    // 道具庫存翻譯
    poopItemInventory: 'Poop Item Inventory',
    totalPoopCount: 'Total Poop Count',
    itemQuantity: 'Item Quantity',
    noItemsYet: 'No items yet',
    recordPoopToGetItems: 'Record poop to get items!',
    monthlyStats: 'Monthly Stats',
    allTimeStats: 'All Time Stats',
  },
  'zh-TW': {
    loginWithGoogle: '使用 Google 登入',
    logout: '登出',
    dropPoop: '拉一坨',
    dropping: '拉屎中...',
    locationError: '無法獲取位置。請開啟權限。',
    welcome: '歡迎',
    totalDrops: '總共拉了',
    noDropsYet: '你還沒拉過任何屎。',
    poopMap: '便便地圖',
    language: '語言',
    poopDetails: '便便詳情',
    location: '地點',
    customLocation: '自訂地點',
    rating: '體驗評分',
    uploadPhoto: '上傳照片',
    notes: '備註',
    save: '儲存',
    cancel: '取消',
    excellent: '極佳',
    good: '良好',
    average: '普通',
    poor: '不佳',
    terrible: '糟糕',
    gettingLocation: '獲取位置中...',
    takingPhoto: '拍照中...',
    friends: '好友',
    addFriend: '加好友',
    friendRequests: '好友邀請',
    privacy: '隱私設定',
    private: '私人',
    friendsOnly: '僅好友可見',
    public: '公開',
    shareViaEmail: '透過電子郵件分享',
    shareViaQR: '透過 QR Code 分享',
    shareViaLink: '透過連結分享',
    inviteFriend: '邀請好友',
    acceptRequest: '接受',
    rejectRequest: '拒絕',
    myQRCode: '我的 QR Code',
    scanQRCode: '掃描 QR Code',
    // 互動功能翻譯
    like: '按讚',
    unlike: '取消讚',
    comment: '留言',
    comments: '留言',
    likes: '讚',
    addComment: '新增留言',
    writeComment: '寫個留言...',
    postComment: '發布',
    deleteComment: '刪除',
    likedBy: '按讚者',
    noComments: '還沒有留言',
    noLikes: '還沒有人按讚',
    // 便便可見性篩選器翻譯
    allPoops: '全部便便',
    myPoops: '我的便便',
    friendPoops: '朋友便便',
    publicPoops: '公開便便',
    poopVisibility: '便便可見性',
    selectPoopType: '選擇要顯示的便便類型',
    showAllVisible: '顯示所有可見的便便',
    showMyPoops: '只顯示我的便便記錄',
    showFriendPoops: '只顯示朋友的便便',
    showPublicPoops: '只顯示公開的便便',
    switchVisibilityTip: '切換可見性來減少地圖上的便便數量',
    // 社交功能翻譯
    leaderboard: '排行榜',
    achievements: '成就',
    feed: '動態牆',
    challenges: '挑戰',
    notifications: '通知',
    statistics: '統計',
    weeklyStats: '週統計',
    // Header 統計翻譯
    today: '今天',
    week: '本週',
    total: '總計',
    iconLegend: '圖標說明',
    myPoop: '我的便便',
    friendPoop: '好友的便便',
    publicPoop: '公開的便便',
    poopHistory: '便便歷史',
    weeklyTrend: '本週趨勢',
    // 社交菜單翻譯
    socialFeatures: '社交功能',
    selectFeature: '選擇要使用的功能',
    viewPoopRanking: '查看便便排名',
    myAchievementProgress: '我的成就進度',
    friendActivity: '朋友動態',
    participateInChallenges: '參與挑戰',
    messageNotifications: '消息通知',
    recordPoopToUnlock: '記錄便便來解鎖更多功能',
    // 道具庫存翻譯
    poopItemInventory: '便便道具庫存',
    totalPoopCount: '總便便數',
    itemQuantity: '道具數量',
    noItemsYet: '還沒有任何道具',
    recordPoopToGetItems: '記錄便便來獲得道具吧！',
    monthlyStats: '月統計',
    allTimeStats: '全時統計',
  },
  'zh-CN': {
    loginWithGoogle: '使用 Google 登录',
    logout: '登出',
    dropPoop: '拉一坨',
    dropping: '拉屎中...',
    locationError: '无法获取位置。请开启权限。',
    welcome: '欢迎',
    totalDrops: '总共拉了',
    noDropsYet: '你还没拉过任何屎。',
    poopMap: '便便地图',
    language: '语言',
    poopDetails: '便便详情',
    location: '地点',
    customLocation: '自定义地点',
    rating: '体验评分',
    uploadPhoto: '上传照片',
    notes: '备注',
    save: '保存',
    cancel: '取消',
    excellent: '极佳',
    good: '良好',
    average: '普通',
    poor: '不佳',
    terrible: '糟糕',
    gettingLocation: '获取位置中...',
    takingPhoto: '拍照中...',
    friends: '好友',
    addFriend: '加好友',
    friendRequests: '好友邀请',
    privacy: '隐私设置',
    private: '私人',
    friendsOnly: '仅好友可见',
    public: '公开',
    shareViaEmail: '通过电子邮件分享',
    shareViaQR: '通过二维码分享',
    shareViaLink: '通过链接分享',
    inviteFriend: '邀请好友',
    acceptRequest: '接受',
    rejectRequest: '拒绝',
    myQRCode: '我的二维码',
    scanQRCode: '扫描二维码',
    like: '点赞',
    unlike: '取消赞',
    comment: '留言',
    comments: '留言',
    likes: '赞',
    addComment: '新增留言',
    writeComment: '写个留言...',
    postComment: '发布',
    deleteComment: '删除',
    likedBy: '点赞者',
    noComments: '还没有留言',
    noLikes: '还没有人点赞',
    // 便便可见性筛选器翻译
    allPoops: '全部便便',
    myPoops: '我的便便',
    friendPoops: '朋友便便',
    publicPoops: '公开便便',
    poopVisibility: '便便可见性',
    selectPoopType: '选择要显示的便便类型',
    showAllVisible: '显示所有可见的便便',
    showMyPoops: '只显示我的便便记录',
    showFriendPoops: '只显示朋友的便便',
    showPublicPoops: '只显示公开的便便',
    switchVisibilityTip: '切换可见性来减少地图上的便便数量',
    // 社交功能翻译
    leaderboard: '排行榜',
    achievements: '成就',
    feed: '动态墙',
    challenges: '挑战',
    notifications: '通知',
    statistics: '统计',
    weeklyStats: '周统计',
    // Header 统计翻译
    today: '今天',
    week: '本周',
    total: '总计',
    iconLegend: '图标说明',
    myPoop: '我的便便',
    friendPoop: '好友的便便',
    publicPoop: '公开的便便',
    poopHistory: '便便历史',
    weeklyTrend: '本周趋势',
    // 社交菜单翻译
    socialFeatures: '社交功能',
    selectFeature: '选择要使用的功能',
    viewPoopRanking: '查看便便排名',
    myAchievementProgress: '我的成就进度',
    friendActivity: '朋友动态',
    participateInChallenges: '参与挑战',
    messageNotifications: '消息通知',
    recordPoopToUnlock: '记录便便来解锁更多功能',
    // 道具库存翻译
    poopItemInventory: '便便道具库存',
    totalPoopCount: '总便便数',
    itemQuantity: '道具数量',
    noItemsYet: '还没有任何道具',
    recordPoopToGetItems: '记录便便来获得道具吧！',
    monthlyStats: '月统计',
    allTimeStats: '全时统计',
  },
  ja: {
    loginWithGoogle: 'Googleでログイン',
    logout: 'ログアウト',
    dropPoop: 'うんちを落とす',
    dropping: '落とし中...',
    locationError: '位置情報を取得できません。権限を有効にしてください。',
    welcome: 'ようこそ',
    totalDrops: '総ドロップ数',
    noDropsYet: 'まだうんちを落としていません。',
    poopMap: 'うんちマップ',
    language: '言語',
    poopDetails: 'うんち詳細',
    location: '場所',
    customLocation: 'カスタム場所',
    rating: '体験評価',
    uploadPhoto: '写真をアップロード',
    notes: 'メモ',
    save: '保存',
    cancel: 'キャンセル',
    excellent: '素晴らしい',
    good: '良い',
    average: '普通',
    poor: '悪い',
    terrible: 'ひどい',
    gettingLocation: '位置取得中...',
    takingPhoto: '写真撮影中...',
    friends: '友達',
    addFriend: '友達を追加',
    friendRequests: '友達リクエスト',
    privacy: 'プライバシー設定',
    private: 'プライベート',
    friendsOnly: '友達のみ',
    public: '公開',
    shareViaEmail: 'メールで共有',
    shareViaQR: 'QRコードで共有',
    shareViaLink: 'リンクで共有',
    inviteFriend: '友達を招待',
    acceptRequest: '承認',
    rejectRequest: '拒否',
    myQRCode: '私のQRコード',
    scanQRCode: 'QRコードをスキャン',
    like: 'いいね',
    unlike: 'いいね取消',
    comment: 'コメント',
    comments: 'コメント',
    likes: 'いいね',
    addComment: 'コメント追加',
    writeComment: 'コメントを書く...',
    postComment: '投稿',
    deleteComment: '削除',
    likedBy: 'いいねした人',
    noComments: 'まだコメントがありません',
    noLikes: 'まだいいねがありません',
    // うんち可視性フィルター翻訳
    allPoops: 'すべてのうんち',
    myPoops: '私のうんち',
    friendPoops: '友達のうんち',
    publicPoops: '公開うんち',
    poopVisibility: 'うんち可視性',
    selectPoopType: '表示するうんちタイプを選択',
    showAllVisible: 'すべての可視うんちを表示',
    showMyPoops: '私のうんち記録のみ表示',
    showFriendPoops: '友達のうんちのみ表示',
    showPublicPoops: '公開うんちのみ表示',
    switchVisibilityTip: '可視性を切り替えてマップ上のうんちを減らす',
    // ソーシャル機能翻訳
    leaderboard: 'リーダーボード',
    achievements: '実績',
    feed: 'フィード',
    challenges: 'チャレンジ',
    notifications: '通知',
    statistics: '統計',
    weeklyStats: '週間統計',
    // Header 統計翻訳
    today: '今日',
    week: '今週',
    total: '合計',
    iconLegend: 'アイコン説明',
    myPoop: '私のうんち',
    friendPoop: '友達のうんち',
    publicPoop: '公開うんち',
    poopHistory: 'うんち履歴',
    weeklyTrend: '今週の傾向',
    // ソーシャルメニュー翻訳
    socialFeatures: 'ソーシャル機能',
    selectFeature: '使用する機能を選択',
    viewPoopRanking: 'うんちランキングを見る',
    myAchievementProgress: '私の実績進度',
    friendActivity: '友達の活動',
    participateInChallenges: 'チャレンジに参加',
    messageNotifications: 'メッセージ通知',
    recordPoopToUnlock: 'うんちを記録してより多くの機能を解除',
    // アイテム在庫翻訳
    poopItemInventory: 'うんちアイテム在庫',
    totalPoopCount: '総うんち数',
    itemQuantity: 'アイテム数量',
    noItemsYet: 'まだアイテムがありません',
    recordPoopToGetItems: 'うんちを記録してアイテムを獲得しよう！',
    monthlyStats: '月間統計',
    allTimeStats: '全期間統計',
  },
  ko: {
    loginWithGoogle: 'Google로 로그인',
    logout: '로그아웃',
    dropPoop: '똥 떨구기',
    dropping: '떨구는 중...',
    locationError: '위치를 가져올 수 없습니다. 권한을 활성화해주세요.',
    welcome: '환영합니다',
    totalDrops: '총 드롭 수',
    noDropsYet: '아직 똥을 떨구지 않았습니다.',
    poopMap: '똥 지도',
    language: '언어',
    poopDetails: '똥 상세정보',
    location: '위치',
    customLocation: '사용자 정의 위치',
    rating: '경험 평가',
    uploadPhoto: '사진 업로드',
    notes: '메모',
    save: '저장',
    cancel: '취소',
    excellent: '훌륭함',
    good: '좋음',
    average: '보통',
    poor: '나쁨',
    terrible: '끔찍함',
    gettingLocation: '위치 가져오는 중...',
    takingPhoto: '사진 촬영 중...',
    friends: '친구',
    addFriend: '친구 추가',
    friendRequests: '친구 요청',
    privacy: '개인정보 설정',
    private: '비공개',
    friendsOnly: '친구만',
    public: '공개',
    shareViaEmail: '이메일로 공유',
    shareViaQR: 'QR 코드로 공유',
    shareViaLink: '링크로 공유',
    inviteFriend: '친구 초대',
    acceptRequest: '수락',
    rejectRequest: '거절',
    myQRCode: '내 QR 코드',
    scanQRCode: 'QR 코드 스캔',
    like: '좋아요',
    unlike: '좋아요 취소',
    comment: '댓글',
    comments: '댓글',
    likes: '좋아요',
    addComment: '댓글 추가',
    writeComment: '댓글을 작성하세요...',
    postComment: '게시',
    deleteComment: '삭제',
    likedBy: '좋아요한 사람',
    noComments: '아직 댓글이 없습니다',
    noLikes: '아직 좋아요가 없습니다',
    // 똥 가시성 필터 번역
    allPoops: '모든 똥',
    myPoops: '내 똥',
    friendPoops: '친구 똥',
    publicPoops: '공개 똥',
    poopVisibility: '똥 가시성',
    selectPoopType: '표시할 똥 유형 선택',
    showAllVisible: '모든 보이는 똥 표시',
    showMyPoops: '내 똥 기록만 표시',
    showFriendPoops: '친구 똥만 표시',
    showPublicPoops: '공개 똥만 표시',
    switchVisibilityTip: '가시성을 전환하여 지도의 똥 수를 줄이세요',
    // 소셜 기능 번역
    leaderboard: '리더보드',
    achievements: '업적',
    feed: '피드',
    challenges: '도전',
    notifications: '알림',
    statistics: '통계',
    weeklyStats: '주간 통계',
    monthlyStats: '월간 통계',
    allTimeStats: '전체 통계',
    // Header 통계 번역
    today: '오늘',
    week: '이번 주',
    total: '총계',
    iconLegend: '아이콘 설명',
    myPoop: '내 똥',
    friendPoop: '친구 똥',
    publicPoop: '공개 똥',
    poopHistory: '똥 기록',
    weeklyTrend: '주간 추세',
    // 소셜 메뉴 번역
    socialFeatures: '소셜 기능',
    selectFeature: '사용할 기능 선택',
    viewPoopRanking: '똥 순위 보기',
    myAchievementProgress: '내 업적 진도',
    friendActivity: '친구 활동',
    participateInChallenges: '도전에 참여',
    messageNotifications: '메시지 알림',
    recordPoopToUnlock: '똥을 기록하여 더 많은 기능 해제',
    // 아이템 인벤토리 번역
    poopItemInventory: '똥 아이템 인벤토리',
    totalPoopCount: '총 똥 수',
    itemQuantity: '아이템 수량',
    noItemsYet: '아직 아이템이 없습니다',
    recordPoopToGetItems: '똥을 기록하여 아이템을 얻으세요!',
  },
  es: {
    loginWithGoogle: 'Iniciar sesión con Google',
    logout: 'Cerrar sesión',
    dropPoop: 'Soltar una Caca',
    dropping: 'Soltando...',
    locationError: 'No se pudo obtener la ubicación. Habilite los permisos.',
    welcome: 'Bienvenido',
    totalDrops: 'Gotas Totales',
    noDropsYet: 'Aún no has soltado ninguna caca.',
    poopMap: 'Mapa de Caca',
    language: 'Idioma',
    poopDetails: 'Detalles de Caca',
    location: 'Ubicación',
    customLocation: 'Ubicación Personalizada',
    rating: 'Calificación de Experiencia',
    uploadPhoto: 'Subir Foto',
    notes: 'Notas',
    save: 'Guardar',
    cancel: 'Cancelar',
    excellent: 'Excelente',
    good: 'Bueno',
    average: 'Promedio',
    poor: 'Malo',
    terrible: 'Terrible',
    gettingLocation: 'Obteniendo ubicación...',
    takingPhoto: 'Tomando foto...',
    friends: 'Amigos',
    addFriend: 'Agregar Amigo',
    friendRequests: 'Solicitudes de Amistad',
    privacy: 'Configuración de Privacidad',
    private: 'Privado',
    friendsOnly: 'Solo Amigos',
    public: 'Público',
    shareViaEmail: 'Compartir por Email',
    shareViaQR: 'Compartir por Código QR',
    shareViaLink: 'Compartir por Enlace',
    inviteFriend: 'Invitar Amigo',
    acceptRequest: 'Aceptar',
    rejectRequest: 'Rechazar',
    myQRCode: 'Mi Código QR',
    scanQRCode: 'Escanear Código QR',
    like: 'Me Gusta',
    unlike: 'No Me Gusta',
    comment: 'Comentario',
    comments: 'Comentarios',
    likes: 'Me Gusta',
    addComment: 'Agregar Comentario',
    writeComment: 'Escribe un comentario...',
    postComment: 'Publicar',
    deleteComment: 'Eliminar',
    likedBy: 'Le gustó a',
    noComments: 'Aún no hay comentarios',
    noLikes: 'Aún no hay me gusta',
    // Filtro de visibilidad de caca
    allPoops: 'Todas las Cacas',
    myPoops: 'Mis Cacas',
    friendPoops: 'Cacas de Amigos',
    publicPoops: 'Cacas Públicas',
    poopVisibility: 'Visibilidad de Caca',
    selectPoopType: 'Seleccionar tipo de caca a mostrar',
    showAllVisible: 'Mostrar todas las cacas visibles',
    showMyPoops: 'Mostrar solo mis registros de caca',
    showFriendPoops: 'Mostrar solo cacas de amigos',
    showPublicPoops: 'Mostrar solo cacas públicas',
    switchVisibilityTip: 'Cambiar visibilidad para reducir cacas en el mapa',
    // Funciones sociales
    leaderboard: 'Tabla de Clasificación',
    achievements: 'Logros',
    feed: 'Feed',
    challenges: 'Desafíos',
    notifications: 'Notificaciones',
    statistics: 'Estadísticas',
    weeklyStats: 'Estadísticas Semanales',
    monthlyStats: 'Estadísticas Mensuales',
    allTimeStats: 'Estadísticas de Todos los Tiempos',
    // Header estadísticas traducción
    today: 'Hoy',
    week: 'Semana',
    total: 'Total',
    iconLegend: 'Leyenda de Iconos',
    myPoop: 'Mi Caca',
    friendPoop: 'Caca de Amigo',
    publicPoop: 'Caca Pública',
    poopHistory: 'Historial de Caca',
    weeklyTrend: 'Tendencia Semanal',
    // Menú social traducción
    socialFeatures: 'Funciones Sociales',
    selectFeature: 'Seleccionar función a usar',
    viewPoopRanking: 'Ver ranking de caca',
    myAchievementProgress: 'Mi progreso de logros',
    friendActivity: 'Actividad de amigos',
    participateInChallenges: 'Participar en desafíos',
    messageNotifications: 'Notificaciones de mensajes',
    recordPoopToUnlock: 'Registra caca para desbloquear más funciones',
    // Inventario de artículos traducción
    poopItemInventory: 'Inventario de Artículos de Caca',
    totalPoopCount: 'Conteo Total de Caca',
    itemQuantity: 'Cantidad de Artículos',
    noItemsYet: 'Aún no hay artículos',
    recordPoopToGetItems: '¡Registra caca para obtener artículos!',
  },
  fr: {
    loginWithGoogle: 'Se connecter avec Google',
    logout: 'Se déconnecter',
    dropPoop: 'Lâcher un Caca',
    dropping: 'Lâchage...',
    locationError: 'Impossible d\'obtenir la localisation. Veuillez activer les permissions.',
    welcome: 'Bienvenue',
    totalDrops: 'Gouttes Totales',
    noDropsYet: 'Vous n\'avez pas encore lâché de caca.',
    poopMap: 'Carte de Caca',
    language: 'Langue',
    poopDetails: 'Détails du Caca',
    location: 'Emplacement',
    customLocation: 'Emplacement Personnalisé',
    rating: 'Évaluation d\'Expérience',
    uploadPhoto: 'Télécharger Photo',
    notes: 'Notes',
    save: 'Sauvegarder',
    cancel: 'Annuler',
    excellent: 'Excellent',
    good: 'Bon',
    average: 'Moyen',
    poor: 'Mauvais',
    terrible: 'Terrible',
    gettingLocation: 'Obtention de la localisation...',
    takingPhoto: 'Prise de photo...',
    friends: 'Amis',
    addFriend: 'Ajouter Ami',
    friendRequests: 'Demandes d\'Amitié',
    privacy: 'Paramètres de Confidentialité',
    private: 'Privé',
    friendsOnly: 'Amis Seulement',
    public: 'Public',
    shareViaEmail: 'Partager par Email',
    shareViaQR: 'Partager par Code QR',
    shareViaLink: 'Partager par Lien',
    inviteFriend: 'Inviter Ami',
    acceptRequest: 'Accepter',
    rejectRequest: 'Rejeter',
    myQRCode: 'Mon Code QR',
    scanQRCode: 'Scanner Code QR',
    like: 'J\'aime',
    unlike: 'Je n\'aime plus',
    comment: 'Commentaire',
    comments: 'Commentaires',
    likes: 'J\'aime',
    addComment: 'Ajouter Commentaire',
    writeComment: 'Écrire un commentaire...',
    postComment: 'Publier',
    deleteComment: 'Supprimer',
    likedBy: 'Aimé par',
    noComments: 'Pas encore de commentaires',
    noLikes: 'Pas encore de j\'aime',
    // Filtre de visibilité de caca
    allPoops: 'Tous les Cacas',
    myPoops: 'Mes Cacas',
    friendPoops: 'Cacas d\'Amis',
    publicPoops: 'Cacas Publics',
    poopVisibility: 'Visibilité de Caca',
    selectPoopType: 'Sélectionner le type de caca à afficher',
    showAllVisible: 'Afficher tous les cacas visibles',
    showMyPoops: 'Afficher seulement mes enregistrements de caca',
    showFriendPoops: 'Afficher seulement les cacas d\'amis',
    showPublicPoops: 'Afficher seulement les cacas publics',
    switchVisibilityTip: 'Changer la visibilité pour réduire les cacas sur la carte',
    // Fonctions sociales
    leaderboard: 'Classement',
    achievements: 'Réalisations',
    feed: 'Fil d\'actualité',
    challenges: 'Défis',
    notifications: 'Notifications',
    statistics: 'Statistiques',
    weeklyStats: 'Statistiques Hebdomadaires',
    monthlyStats: 'Statistiques Mensuelles',
    allTimeStats: 'Statistiques de Tous les Temps',
    // Header statistiques traduction
    today: 'Aujourd\'hui',
    week: 'Semaine',
    total: 'Total',
    iconLegend: 'Légende des Icônes',
    myPoop: 'Mon Caca',
    friendPoop: 'Caca d\'Ami',
    publicPoop: 'Caca Public',
    poopHistory: 'Historique de Caca',
    weeklyTrend: 'Tendance Hebdomadaire',
    // Menu social traduction
    socialFeatures: 'Fonctions Sociales',
    selectFeature: 'Sélectionner la fonction à utiliser',
    viewPoopRanking: 'Voir le classement de caca',
    myAchievementProgress: 'Mon progrès de réalisations',
    friendActivity: 'Activité des amis',
    participateInChallenges: 'Participer aux défis',
    messageNotifications: 'Notifications de messages',
    recordPoopToUnlock: 'Enregistrer caca pour débloquer plus de fonctions',
    // Inventaire d\'articles traduction
    poopItemInventory: 'Inventaire d\'Articles de Caca',
    totalPoopCount: 'Nombre Total de Caca',
    itemQuantity: 'Quantité d\'Articles',
    noItemsYet: 'Pas encore d\'articles',
    recordPoopToGetItems: 'Enregistrez caca pour obtenir des articles!',
  },
  de: {
    loginWithGoogle: 'Mit Google anmelden',
    logout: 'Abmelden',
    dropPoop: 'Einen Haufen fallen lassen',
    dropping: 'Fallenlassen...',
    locationError: 'Standort konnte nicht ermittelt werden. Bitte Berechtigungen aktivieren.',
    welcome: 'Willkommen',
    totalDrops: 'Gesamte Tropfen',
    noDropsYet: 'Du hast noch keinen Haufen fallen gelassen.',
    poopMap: 'Haufen-Karte',
    language: 'Sprache',
    poopDetails: 'Haufen-Details',
    location: 'Standort',
    customLocation: 'Benutzerdefinierter Standort',
    rating: 'Erfahrungsbewertung',
    uploadPhoto: 'Foto hochladen',
    notes: 'Notizen',
    save: 'Speichern',
    cancel: 'Abbrechen',
    excellent: 'Ausgezeichnet',
    good: 'Gut',
    average: 'Durchschnittlich',
    poor: 'Schlecht',
    terrible: 'Schrecklich',
    gettingLocation: 'Standort wird ermittelt...',
    takingPhoto: 'Foto wird aufgenommen...',
    friends: 'Freunde',
    addFriend: 'Freund hinzufügen',
    friendRequests: 'Freundschaftsanfragen',
    privacy: 'Datenschutzeinstellungen',
    private: 'Privat',
    friendsOnly: 'Nur Freunde',
    public: 'Öffentlich',
    shareViaEmail: 'Per E-Mail teilen',
    shareViaQR: 'Per QR-Code teilen',
    shareViaLink: 'Per Link teilen',
    inviteFriend: 'Freund einladen',
    acceptRequest: 'Akzeptieren',
    rejectRequest: 'Ablehnen',
    myQRCode: 'Mein QR-Code',
    scanQRCode: 'QR-Code scannen',
    like: 'Gefällt mir',
    unlike: 'Gefällt mir nicht mehr',
    comment: 'Kommentar',
    comments: 'Kommentare',
    likes: 'Gefällt mir',
    addComment: 'Kommentar hinzufügen',
    writeComment: 'Schreibe einen Kommentar...',
    postComment: 'Veröffentlichen',
    deleteComment: 'Löschen',
    likedBy: 'Gefällt',
    noComments: 'Noch keine Kommentare',
    noLikes: 'Noch keine Likes',
    // Haufen-Sichtbarkeitsfilter
    allPoops: 'Alle Haufen',
    myPoops: 'Meine Haufen',
    friendPoops: 'Freunde Haufen',
    publicPoops: 'Öffentliche Haufen',
    poopVisibility: 'Haufen-Sichtbarkeit',
    selectPoopType: 'Haufen-Typ zum Anzeigen auswählen',
    showAllVisible: 'Alle sichtbaren Haufen anzeigen',
    showMyPoops: 'Nur meine Haufen-Aufzeichnungen anzeigen',
    showFriendPoops: 'Nur Freunde-Haufen anzeigen',
    showPublicPoops: 'Nur öffentliche Haufen anzeigen',
    switchVisibilityTip: 'Sichtbarkeit wechseln, um Haufen auf der Karte zu reduzieren',
    // Soziale Funktionen
    leaderboard: 'Bestenliste',
    achievements: 'Erfolge',
    feed: 'Feed',
    challenges: 'Herausforderungen',
    notifications: 'Benachrichtigungen',
    statistics: 'Statistiken',
    weeklyStats: 'Wöchentliche Statistiken',
    monthlyStats: 'Monatliche Statistiken',
    allTimeStats: 'Alle Zeit Statistiken',
    // Header Statistiken Übersetzung
    today: 'Heute',
    week: 'Woche',
    total: 'Gesamt',
    iconLegend: 'Symbol-Legende',
    myPoop: 'Mein Haufen',
    friendPoop: 'Freund Haufen',
    publicPoop: 'Öffentlicher Haufen',
    poopHistory: 'Haufen-Verlauf',
    weeklyTrend: 'Wöchentlicher Trend',
    // Soziales Menü Übersetzung
    socialFeatures: 'Soziale Funktionen',
    selectFeature: 'Funktion zum Verwenden auswählen',
    viewPoopRanking: 'Haufen-Ranking anzeigen',
    myAchievementProgress: 'Mein Erfolgsfortschritt',
    friendActivity: 'Freunde-Aktivität',
    participateInChallenges: 'An Herausforderungen teilnehmen',
    messageNotifications: 'Nachrichten-Benachrichtigungen',
    recordPoopToUnlock: 'Haufen aufzeichnen, um mehr Funktionen freizuschalten',
    // Artikel-Inventar Übersetzung
    poopItemInventory: 'Haufen-Artikel-Inventar',
    totalPoopCount: 'Gesamte Haufen-Anzahl',
    itemQuantity: 'Artikel-Menge',
    noItemsYet: 'Noch keine Artikel',
    recordPoopToGetItems: 'Haufen aufzeichnen, um Artikel zu erhalten!',
  },
};
