import { Translations } from './types';

export const translations: Translations = {
  en: {
    loginWithGoogle: 'Login with Google',
    logout: 'Logout',
    dropPoop: 'Drop a Poop',
    dropping: 'Dropping...',
    locationError: 'Could not get location. Please enable permissions.',
    welcome: 'Welcome',
    totalDrops: 'Total Drops',
    noDropsYet: "You haven't dropped any poops yet.",
    poopMap: 'Poop Map',
    language: 'Language',
    poopDetails: 'Poop Details',
    location: 'Location',
    customLocation: 'Custom Location',
    rating: 'Experience Rating',
    uploadPhoto: 'Upload Photo',
    notes: 'Notes',
    save: 'Save',
    cancel: 'Cancel',
    excellent: 'Excellent',
    good: 'Good',
    average: 'Average',
    poor: 'Poor',
    terrible: 'Terrible',
    gettingLocation: 'Getting location...',
    takingPhoto: 'Taking photo...',
    friends: 'Friends',
    addFriend: 'Add Friend',
    friendRequests: 'Friend Requests',
    privacy: 'Privacy',
    private: 'Private',
    friendsOnly: 'Friends Only',
    public: 'Public',
    shareViaEmail: 'Share via Email',
    shareViaQR: 'Share via QR Code',
    shareViaLink: 'Share via Link',
    inviteFriend: 'Invite Friend',
    acceptRequest: 'Accept',
    rejectRequest: 'Reject',
    myQRCode: 'My QR Code',
    scanQRCode: 'Scan QR Code',
    // 互動功能翻譯
    like: 'Like',
    unlike: 'Unlike',
    comment: 'Comment',
    comments: 'Comments',
    likes: 'Likes',
    addComment: 'Add Comment',
    writeComment: 'Write a comment...',
    postComment: 'Post',
    deleteComment: 'Delete',
    likedBy: 'Liked by',
    noComments: 'No comments yet',
    noLikes: 'No likes yet',
  },
  'zh-TW': {
    loginWithGoogle: '使用 Google 登入',
    logout: '登出',
    dropPoop: '拉一坨',
    dropping: '拉屎中...',
    locationError: '無法獲取位置。請開啟權限。',
    welcome: '歡迎',
    totalDrops: '總共拉了',
    noDropsYet: '你還沒拉過任何屎。',
    poopMap: '便便地圖',
    language: '語言',
    poopDetails: '便便詳情',
    location: '地點',
    customLocation: '自訂地點',
    rating: '體驗評分',
    uploadPhoto: '上傳照片',
    notes: '備註',
    save: '儲存',
    cancel: '取消',
    excellent: '極佳',
    good: '良好',
    average: '普通',
    poor: '不佳',
    terrible: '糟糕',
    gettingLocation: '獲取位置中...',
    takingPhoto: '拍照中...',
    friends: '好友',
    addFriend: '加好友',
    friendRequests: '好友邀請',
    privacy: '隱私設定',
    private: '私人',
    friendsOnly: '僅好友可見',
    public: '公開',
    shareViaEmail: '透過電子郵件分享',
    shareViaQR: '透過 QR Code 分享',
    shareViaLink: '透過連結分享',
    inviteFriend: '邀請好友',
    acceptRequest: '接受',
    rejectRequest: '拒絕',
    myQRCode: '我的 QR Code',
    scanQRCode: '掃描 QR Code',
    // 互動功能翻譯
    like: '按讚',
    unlike: '取消讚',
    comment: '留言',
    comments: '留言',
    likes: '讚',
    addComment: '新增留言',
    writeComment: '寫個留言...',
    postComment: '發布',
    deleteComment: '刪除',
    likedBy: '按讚者',
    noComments: '還沒有留言',
    noLikes: '還沒有人按讚',
  },
  'zh-CN': {
    loginWithGoogle: '使用 Google 登录',
    logout: '登出',
    dropPoop: '拉一坨',
    dropping: '拉屎中...',
    locationError: '无法获取位置。请开启权限。',
    welcome: '欢迎',
    totalDrops: '总共拉了',
    noDropsYet: '你还没拉过任何屎。',
    poopMap: '便便地图',
    language: '语言',
  },
  ja: {
    loginWithGoogle: 'Googleでログイン',
    logout: 'ログアウト',
    dropPoop: 'うんちを落とす',
    dropping: '落とし中...',
    locationError: '位置情報を取得できません。権限を有効にしてください。',
    welcome: 'ようこそ',
    totalDrops: '総ドロップ数',
    noDropsYet: 'まだうんちを落としていません。',
    poopMap: 'うんちマップ',
    language: '言語',
  },
  ko: {
    loginWithGoogle: 'Google로 로그인',
    logout: '로그아웃',
    dropPoop: '똥 떨구기',
    dropping: '떨구는 중...',
    locationError: '위치를 가져올 수 없습니다. 권한을 활성화해주세요.',
    welcome: '환영합니다',
    totalDrops: '총 드롭 수',
    noDropsYet: '아직 똥을 떨구지 않았습니다.',
    poopMap: '똥 지도',
    language: '언어',
  },
  es: {
    loginWithGoogle: 'Iniciar sesión con Google',
    logout: 'Cerrar sesión',
    dropPoop: 'Soltar una Caca',
    dropping: 'Soltando...',
    locationError: 'No se pudo obtener la ubicación. Habilite los permisos.',
    welcome: 'Bienvenido',
    totalDrops: 'Gotas Totales',
    noDropsYet: 'Aún no has soltado ninguna caca.',
    poopMap: 'Mapa de Caca',
    language: 'Idioma',
  },
  fr: {
    loginWithGoogle: 'Se connecter avec Google',
    logout: 'Se déconnecter',
    dropPoop: 'Lâcher un Caca',
    dropping: 'Lâchage...',
    locationError: 'Impossible d\'obtenir la localisation. Veuillez activer les permissions.',
    welcome: 'Bienvenue',
    totalDrops: 'Gouttes Totales',
    noDropsYet: 'Vous n\'avez pas encore lâché de caca.',
    poopMap: 'Carte de Caca',
    language: 'Langue',
  },
  de: {
    loginWithGoogle: 'Mit Google anmelden',
    logout: 'Abmelden',
    dropPoop: 'Einen Haufen fallen lassen',
    dropping: 'Fallenlassen...',
    locationError: 'Standort konnte nicht ermittelt werden. Bitte Berechtigungen aktivieren.',
    welcome: 'Willkommen',
    totalDrops: 'Gesamte Tropfen',
    noDropsYet: 'Du hast noch keinen Haufen fallen gelassen.',
    poopMap: 'Haufen-Karte',
    language: 'Sprache',
  },
};
